# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "baoKDtgOqp+qfdLJvt8XXY+cM2ovn1/x1PKOYcKf5CaUlkbyEtfSL2aCRHqIq0a7g9zUcbynuhm9xoZIipuAXeUBILJPiaKpfhWUdW3qk8jWn13nEE6hHcPn0HCj/R8dhB8Dz3I8/6YZaTZIdrPzixbRo9C9ClhIB5aaZDzA6XugUreB70bwaEoamK7cOx0ALiiZ2eR7bhTWSC3O0J5XkyATjbVbssweX7I0j4you+ac3I41K1Sm7PNOIduNIC18FJnkbjtAjXqTC98dP3T0jOh3Lncbq5Xv/noHcX113tNBJ21P6BygRe2fjCwOCad0Aui+qeRzxe7mqROyjps0xJeU5jD7aFfO9Z5r1m18vY/MQF8VpLK22x7aNZ7zPGcTlZiwtjNNcE86yh7j9lm2w1ou1G9XqnDusY4KkhWfxWDsawVnVA7u5QDdPv7qN67ctUbcIfD/S2vhnFwOK2LuYYWYLhoCZvW9OXArJaV3U1xak7R0bRKXL/VXJmYrOhC81gqCQFqcOgCX5MtiAD/gPzaUGcIDLTC/ALLoWHWdO6cLIngkIXBpmNCLNnoaC3inqyFncQNh9dfy+Axe6D1pFH8kKtYUDhjoOBtKiLCQATcsynWw4q1+sYENdKBIAhCDkQ+u7TNDcx3szAiUGsncbzcnusp1jZze8+uB9k7H9Mw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml